"use client";
import {useEffect,useRef,useState} from "react";
import {Play,Pause,SkipBack,SkipForward,Repeat2,Volume2} from "lucide-react";
import {Progress} from "@/components/ui/progress";
import {Switch} from "@/components/ui/switch";
import {Choice} from "./practice";
import {toast} from "sonner";
export type AudioLine={speaker:string;text:string};
export function SpeechPlayer({lines,shadow=false,showText=true,onFinished}:{lines:AudioLine[];shadow?:boolean;showText?:boolean;onFinished?:()=>void}){
 const [current,setCurrent]=useState(0),[playing,setPlaying]=useState(false),[rate,setRate]=useState("0.85×"),[accent,setAccent]=useState("British"),[loop,setLoop]=useState(false),[yourTurn,setYourTurn]=useState(false);
 const alive=useRef(true),playingRef=useRef(false),indexRef=useRef(0),generation=useRef(0),utterance=useRef<SpeechSynthesisUtterance|null>(null),latest=useRef({rate,accent,loop,shadow,onFinished,lines});
 latest.current={rate,accent,loop,shadow,onFinished,lines};
 function stop(){generation.current++;playingRef.current=false;setPlaying(false);window.speechSynthesis?.cancel();}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;playingRef.current=false;window.speechSynthesis?.cancel()}},[]);
 function playLine(index:number){if(!window.speechSynthesis){toast.error("В этом браузере нет озвучивания. Попробуй Chrome, Edge или Safari.");return;}generation.current++;const gen=generation.current;window.speechSynthesis.cancel();const options=latest.current;const line=options.lines[index];if(!line)return;setCurrent(index);indexRef.current=index;setPlaying(true);playingRef.current=true;setYourTurn(false);const u=new SpeechSynthesisUtterance(line.text);u.rate=parseFloat(options.rate);u.lang=options.accent==="British"?"en-GB":"en-US";const voices=window.speechSynthesis.getVoices();const preferred=voices.filter(v=>v.lang===u.lang);u.voice=preferred[index%Math.max(1,preferred.length)]||voices.find(v=>v.lang.startsWith("en"))||null;utterance.current=u;
 u.onend=()=>{if(!alive.current||gen!==generation.current)return;if(options.shadow){playingRef.current=false;setPlaying(false);setYourTurn(true);if(index===options.lines.length-1)options.onFinished?.();return;}if(options.loop){playLine(index);return;}if(index+1<options.lines.length)playLine(index+1);else{playingRef.current=false;setPlaying(false);options.onFinished?.();}};
 u.onerror=e=>{if(!alive.current||gen!==generation.current)return;if(e.error!=="interrupted"&&e.error!=="canceled"){setPlaying(false);playingRef.current=false;toast.error("Голос не воспроизводится. Выбери другой вариант произношения и попробуй снова.")}};window.speechSynthesis.speak(u);}
 function toggle(){if(playing){if(window.speechSynthesis.paused){window.speechSynthesis.resume()}else{window.speechSynthesis.pause();setPlaying(false)}}else if(window.speechSynthesis?.paused&&utterance.current){window.speechSynthesis.resume();setPlaying(true)}else playLine(current);}
 return <div className={"speech-player "+(shadow?"shadow-player":"")}><div className="player-options"><span><Volume2 size={17}/> {shadow?"Listen → pause → repeat":"Синтез речи браузера"}</span><Choice label="Скорость воспроизведения" value={rate} onChange={v=>{stop();setRate(v)}} items={["0.7×","0.85×","1×","1.15×"]}/><Choice label="Вариант произношения" value={accent} onChange={v=>{stop();setAccent(v)}} items={["British","American"]}/></div><div className="player-main"><button className="icon-button" aria-label="Предыдущая фраза" disabled={current===0} onClick={()=>playLine(current-1)}><SkipBack size={23}/></button><button className="player-play" aria-label={playing?"Пауза":"Воспроизвести"} onClick={toggle}>{playing?<Pause size={26}/>:<Play size={26} fill="currentColor"/>}</button><button className="icon-button" aria-label="Следующая фраза" disabled={current+1>=lines.length} onClick={()=>playLine(current+1)}><SkipForward size={23}/></button><div className="player-wave" aria-hidden="true">{[8,18,30,15,40,26,19,32,44,25,16,34,22,12,29,39,24,15,8].map((h,i)=><i key={i} className={playing?"active":""} style={{height:h,animationDelay:i*.05+"s"}}/>)}</div><span className="player-count">{current+1}<small> / {lines.length}</small></span></div><Progress value={(current+1)/lines.length*100} aria-label="Позиция фразы"/>{yourTurn&&<div className="your-turn" role="status">Твоя очередь: повтори фразу вслух. <button onClick={()=>playLine(current)}><Repeat2 size={15}/> Ещё раз</button></div>}<div className="player-bottom"><span>Фраза {current+1} из {lines.length}</span>{!shadow&&<label><Switch checked={loop} onCheckedChange={setLoop} aria-label="Повторять фразу"/><Repeat2 size={15}/> Повтор фразы</label>}{shadow&&<button className="text-button" onClick={()=>playLine(current+1<lines.length?current+1:0)}>{current+1<lines.length?"Я повторил — дальше":"Пройти ещё раз"}</button>}</div>
 {showText&&<div className="player-transcript">{lines.map((line,i)=><button key={i} className={i===current?"active":""} onClick={()=>playLine(i)}><span>{line.speaker}</span><p>{line.text}</p><Play size={15}/></button>)}</div>}</div>
}
