"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Bookmark as BookmarkIcon,Download,Volume2,Square} from "lucide-react";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Choice,ViewHeading,type Save} from "./practice";
import {SpeechPlayer} from "./audio-player";
import type {Bookmark} from "./extended-practice";
export const bookCatalog=[
{id:"alice",title:"Alice's Adventures in Wonderland",author:"Lewis Carroll",level:"B2",year:1865,source:"https://www.gutenberg.org/ebooks/11",description:"Необычная страна, игра слов и любопытство Алисы. Небольшая книга для неспешного чтения.",color:"alice"},
{id:"oz",title:"The Wonderful Wizard of Oz",author:"L. Frank Baum",level:"B1–B2",year:1900,source:"https://www.gutenberg.org/ebooks/55",description:"Дороти и её друзья идут по дороге из жёлтого кирпича. Ясное повествование и приключения.",color:"oz"},
{id:"sherlock",title:"The Adventures of Sherlock Holmes",author:"Arthur Conan Doyle",level:"B2–C1",year:1892,source:"https://www.gutenberg.org/ebooks/1661",description:"Двенадцать расследований Холмса: наблюдательность, загадки и английский викторианской эпохи.",color:"sherlock"},
{id:"garden",title:"The Secret Garden",author:"Frances Hodgson Burnett",level:"B2",year:1911,source:"https://www.gutenberg.org/ebooks/113",description:"История о дружбе, заботе и саде, который меняет жизнь. Полный текст на Project Gutenberg.",color:"garden",external:true},
{id:"treasure",title:"Treasure Island",author:"Robert Louis Stevenson",level:"B2–C1",year:1883,source:"https://www.gutenberg.org/ebooks/120",description:"Остров, карта сокровищ и морское приключение. Полный текст на Project Gutenberg.",color:"treasure",external:true},
{id:"little-women",title:"Little Women",author:"Louisa May Alcott",level:"B2–C1",year:1868,source:"https://www.gutenberg.org/ebooks/514",description:"Четыре сестры, мечты и взросление. Полный текст на Project Gutenberg.",color:"women",external:true}
];
export function Books({save,bookmarks}:{save:Save;bookmarks:Bookmark[]}){
 const [selected,setSelected]=useState<typeof bookCatalog[number]|null>(null),[content,setContent]=useState<{pages:string[][]}|null>(null),[page,setPage]=useState(0),[error,setError]=useState(""),[size,setSize]=useState("Обычный"),[sound,setSound]=useState(false),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!selected||selected.external)return;setContent(null);setError("");const c=new AbortController();fetch("/books/"+selected.id+".json",{signal:c.signal}).then(r=>{if(!r.ok)throw new Error("Не удалось открыть книгу. Повтори попытку.");return r.json()}).then(d=>setContent(d as {pages:string[][]})).catch(e=>{if(e.name!=="AbortError")setError(e.message)});return()=>{c.abort();window.speechSynthesis?.cancel()}},[selected,retry]);
 async function bookmark(){if(!selected)return;setSaving(true);try{await save({id:crypto.randomUUID(),action:"bookmark",bookId:selected.id,page});setSaved(true)}catch{setSaved(false)}finally{setSaving(false)}}
 if(selected)return <><button className="text-button back-link" onClick={()=>{setSelected(null);setSound(false)}}><ArrowLeft size={17}/> В книжную библиотеку</button><ViewHeading over={selected.author+" · "+selected.year} title={selected.title} description="Оригинальный английский текст. Читай небольшими фрагментами и сохраняй место."/><div className="book-reader-toolbar"><Choice label="Размер шрифта" value={size} onChange={setSize} items={["Обычный","Крупный","Очень крупный"]}/><button className="text-button" onClick={()=>setSound(!sound)}><Volume2 size={18}/>{sound?"Скрыть озвучивание":"Слушать фрагмент"}</button><a className="text-button" href={"/books/"+selected.id+".txt"} download><Download size={17}/> Весь текст + лицензия</a></div>{error?<div className="empty-state"><p>{error}</p><button className="btn primary" onClick={()=>setRetry(v=>v+1)}>Повторить</button></div>:!content?<div className="empty-state" role="status">Открываем книгу…</div>:<>{sound&&<SpeechPlayer key={selected.id+page} lines={content.pages[Math.min(page,content.pages.length-1)].map(text=>({speaker:selected.author,text}))} showText={false}/>}<article className={"book-reader size-"+(size==="Обычный"?"normal":size==="Крупный"?"large":"xl")}><div className="book-reader-meta"><span>{selected.author}</span><span>Фрагмент {page+1} / {content.pages.length}</span></div>{content.pages[Math.min(page,content.pages.length-1)].map((p,i)=><p key={i}>{p}</p>)}</article><div className="book-pagination"><button className="btn light" disabled={page===0} onClick={()=>{setPage(p=>p-1);setSaved(false);window.speechSynthesis?.cancel();window.scrollTo({top:0,behavior:"instant"})}}><ArrowLeft size={17}/> Назад</button><button className="btn primary" disabled={saving||saved} onClick={bookmark}><BookmarkIcon size={17}/>{saving?"Сохраняем…":saved?"Место сохранено":"Сохранить место"}</button><button className="btn light" disabled={page>=content.pages.length-1} onClick={()=>{setPage(p=>p+1);setSaved(false);window.speechSynthesis?.cancel();window.scrollTo({top:0,behavior:"instant"})}}>Далее <ArrowRight size={17}/></button></div></>}<div className="gutenberg-notice"><a href={selected.source} target="_blank" rel="noreferrer">Project Gutenberg · страница издания <ArrowUpRight size={13}/></a><p>This eBook is for the use of anyone anywhere in the United States and most other parts of the world at no cost and with almost no restrictions whatsoever. You may copy it, give it away or re-use it under the terms of the <a href={"/books/"+selected.id+".txt"} target="_blank" rel="noreferrer">Project Gutenberg License included with this eBook</a> or online at <a href="https://www.gutenberg.org/policy/license.html" target="_blank" rel="noreferrer">www.gutenberg.org</a>. If you are not located in the United States, you will have to check the laws of the country where you are located before using this eBook.</p></div></>;
 return <><ViewHeading over="GET LOST IN A GOOD BOOK" title="Целые миры — на полке" description="Три полные книги внутри ORBIT и ещё три классических произведения на Project Gutenberg."/><div className="books-banner"><BookOpen size={28}/><div><h2>Читай ради истории.</h2><p>Не переводи каждое слово. Начни с одного фрагмента и дай сюжету увлечь тебя.</p></div><span>ORBIT LIBRARY</span></div><div className="books-grid">{bookCatalog.map((book,i)=>{const mark=bookmarks.find(b=>b.bookId===book.id);const inner=<><div className={"book-cover "+book.color}><div className="book-cover-edge"/><span className="book-edition">THE ORBIT READING COLLECTION</span><span className="book-cover-title">{book.title}</span><span className="book-cover-author">{book.author}</span><div className="book-cover-motif"><BookOpen size={40} strokeWidth={1}/></div><span className="book-cover-year">{book.year}</span></div><div className="book-info"><span className="level-badge">{book.level}</span><span className="book-location">{book.external?"На Project Gutenberg":"Читать в ORBIT"}</span><p>{book.description}</p><div><span>{mark?"Продолжить · фрагмент "+(mark.page+1):"Открыть книгу"}</span>{book.external?<ArrowUpRight size={18}/>:<ArrowRight size={18}/>}</div></div></>;return book.external?<a key={book.id} className="book-card" href={book.source} target="_blank" rel="noreferrer">{inner}</a>:<button className="book-card" key={book.id} onClick={()=>{setSelected(book);setPage(mark?.page||0);setSaved(false);setSound(false)}}>{inner}</button>})}</div><p className="source-note">Уровни — ориентир по сложности оригинального текста. Классические книги содержат лексику и реалии своей эпохи. Встроенные издания предоставлены Project Gutenberg вместе с полной лицензией.</p></>
}
