"use client";
import {useEffect,useState} from "react";
import {ArrowRight,ArrowLeft,Check,CheckCircle2,Lock,Volume2,RotateCcw,BookOpen,PenLine,Languages,Mic,Trophy} from "lucide-react";
import {Progress} from "@/components/ui/progress";
import {homeworkWords,homeworkStages,initialHomework,normalizeWord,wordOptions,type HomeworkState} from "./homework-data";
import {speak} from "./practice";
import {HoldMic} from "./speech-tools";
function WordImage({index,hiddenLabel=false}:{index:number;hiddenLabel?:boolean}){return <div className="word-image" role="img" aria-label={hiddenLabel?"Вариант иллюстрации":homeworkWords[index].ru} style={{backgroundPosition:`${index%5*25}% ${Math.floor(index/5)*50}%`}}/>;}
const stepIcons=[BookOpen,PenLine,Languages,Mic];
export function Homework(){const [state,setState]=useState<HomeworkState>(initialHomework),[loading,setLoading]=useState(true),[guest,setGuest]=useState(false),[loadError,setLoadError]=useState(""),[opened,setOpened]=useState(false),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState(""),[correct,setCorrect]=useState(false),[spoken,setSpoken]=useState(false),[skipped,setSkipped]=useState(false),[picture,setPicture]=useState(false),[mistakes,setMistakes]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);setLoadError("");try{const r=await fetch("/api/homework");if(r.status===401){setGuest(true);return;}const d=await r.json() as HomeworkState & {error?:string};if(!r.ok)throw new Error(d.error);setState(d);setGuest(false);}catch(e){setLoadError(e instanceof Error?e.message:"Не удалось загрузить задание.");}finally{setLoading(false);}}
 useEffect(()=>{load();return()=>window.speechSynthesis?.cancel();},[]);
 const word=homeworkWords[state.index],complete=state.stage===4;
 function resetAnswer(){setAnswer("");setFeedback("");setCorrect(false);setSpoken(false);setSkipped(false);setPicture(false);setMistakes(0);setError("");}
 async function advance(restart=false){if(busy)return;setBusy(true);setError("");const index=state.index===14?0:state.index+1;const next=restart?{...initialHomework,revision:state.revision+1}:{...state,index,stage:state.stage+(state.index===14?1:0),mistakes:state.mistakes+mistakes,skipped:state.skipped+(skipped?1:0),revision:state.revision+1};try{if(!guest){const r=await fetch("/api/homework",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...next,restart})});const d=await r.json() as HomeworkState & {error?:string};if(!r.ok)throw new Error(d.error);}setState(next);resetAnswer();if(next.stage===3)speak(homeworkWords[next.index].word);if(restart)setOpened(true);}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить. Попробуйте снова.");}finally{setBusy(false);}}
 function check(value:string,expected:string){if(normalizeWord(value)===normalizeWord(expected)){setCorrect(true);setFeedback("Верно! "+word.word+" — "+word.ru);}else{setMistakes(m=>m+1);setFeedback("Пока не совсем. Правильное слово: "+word.word+" — "+word.ru+". Попробуй ещё раз.");}}
 if(loading)return <section className="surface homework-loading" role="status">Загружаем домашнее задание…</section>;
 if(loadError)return <section className="surface"><p role="alert">{loadError}</p><button className="btn primary" onClick={load}>Повторить загрузку</button></section>;
 return <div className="homework-space"><div className="page-heading"><div><span className="eyebrow">HOMEWORK / VOCABULARY</span><h1>Новые слова. Настоящий прогресс.</h1><p>15 слов, которые пригодятся в твоём следующем путешествии.</p></div><span className="unit-label">UNIT 01 / A1–A2</span></div>{guest&&<div className="guest-note">Тренируйся без входа. Чтобы продолжить в другой день, <a href="/signin-with-chatgpt?return_to=%2F%23homework" target="_top">войди в аккаунт</a> — гостевой результат не сохраняется.</div>}
 {!opened&&!complete?<><section className="assignment-card"><div className="assignment-cover"><WordImage index={4}/><span>THE WORLD<br/>IS YOURS.</span></div><div className="assignment-copy"><span className="eyebrow">ТВОЁ ДОМАШНЕЕ ЗАДАНИЕ</span><h2>Words for your next adventure.</h2><p>Сначала познакомься с каждым словом. Затем напиши его по памяти, выбери перевод и закрепи голосом и картинкой.</p><div className="assignment-meta"><span>15 слов</span><span>4 этапа</span><span>≈ 20 минут</span></div><Progress value={(state.stage*15+state.index)/60*100}/><button className="btn primary" onClick={()=>{setOpened(true);if(state.stage===3)speak(word.word);}}>{state.stage||state.index?"Продолжить задание":"Изучить 15 слов"}<ArrowRight size={18}/></button></div></section><div className="word-preview-grid">{homeworkWords.map(w=><button className="word-preview" key={w.word} onClick={()=>speak(w.word)}><WordImage index={w.image}/><span>{w.word}</span><Volume2 size={15}/></button>)}</div></>:complete?<section className="homework-done"><Trophy size={64}/><span className="eyebrow">UNIT COMPLETE</span><h2>15 слов стали ближе.</h2><p>Ты прошёл карточки, написание, перевод и картинки.</p><div className="completion-stats"><div><b>15</b><span>слов изучено</span></div><div><b>{state.mistakes}</b><span>ошибок с повтором</span></div><div><b>{15-state.skipped}/15</b><span>слов распознано</span></div></div>{state.skipped>0&&<p>Речь пропущена для {state.skipped} слов. Эти ответы не засчитаны как произнесённые.</p>}<button className="btn primary" disabled={busy} onClick={()=>advance(true)}><RotateCcw size={18}/>Повторить набор</button>{error&&<p role="alert">{error}</p>}</section>:<><button className="text-button" onClick={()=>{setOpened(false);window.speechSynthesis?.cancel();}}><ArrowLeft size={16}/>Обзор задания</button><div className="homework-layout"><aside className="homework-steps">{homeworkStages.map((label,i)=>{const Icon=stepIcons[i];return <div key={label} className={i===state.stage?"current":i<state.stage?"done":"locked"}><span>{i<state.stage?<Check size={18}/>:i>state.stage?<Lock size={16}/>:<Icon size={19}/>}</span><div><small>ЭТАП 0{i+1}</small><b>{label}</b></div></div>;})}<div className="homework-tip"><b>Слова остаются те же.</b><p>Каждый этап помогает вспомнить их по-новому.</p></div></aside><section className="word-workbench" key={state.stage+":"+state.index}><div className="word-workbench-top"><span>{homeworkStages[state.stage]}</span><b>{state.index+1}<span> / 15</span></b></div><Progress value={state.index/15*100}/>
 {state.stage===0?<div className="learn-word"><div className="learn-illustration"><WordImage index={state.index}/></div><div className="learn-definition"><span className="word-part">{word.pos}{word.word==="luggage"?" · неисчисляемое":""}</span><h2>{word.word}<button className="pronounce-button" aria-label={"Произнести "+word.word} onClick={()=>speak(word.word)}><Volume2 size={24}/></button></h2><span className="ipa">{word.ipa}</span><h3>{word.ru}</h3><div className="word-example"><span>IN CONTEXT</span><p>{word.en}</p><p lang="ru">{word.example}</p><button className="text-button" onClick={()=>speak(word.en)}><Volume2 size={16}/>Послушать пример</button></div></div></div>:state.stage===1?<div className="word-test"><span className="eyebrow">WRITE THE WORD CORRECTLY</span><h2>{word.ru}</h2><p>Напиши слово на английском.</p><form onSubmit={e=>{e.preventDefault();check(answer,word.word);}}><input autoFocus aria-label="Слово на английском" value={answer} disabled={correct} autoComplete="off" autoCapitalize="none" spellCheck={false} onChange={e=>setAnswer(e.target.value)} placeholder="Your answer…"/>{!correct&&<button className="btn primary" disabled={!answer.trim()}>Проверить <Check size={18}/></button>}</form></div>:state.stage===2?<div className="word-test"><span className="eyebrow">CHOOSE THE TRANSLATION</span><h2>{word.word}<button className="pronounce-button" aria-label="Послушать слово" onClick={()=>speak(word.word)}><Volume2 size={22}/></button></h2><p>Выбери подходящий перевод.</p><div className="translation-options">{wordOptions(state.index).map((i,n)=><button key={i} disabled={correct} onClick={()=>check(homeworkWords[i].word,word.word)}><span>{n+1}</span>{homeworkWords[i].ru}</button>)}</div></div>:<div className="word-test speech-test"><span className="eyebrow">SAY IT. PICTURE IT.</span><h2>{word.word}</h2><button className="btn light" onClick={()=>speak(word.word)}><Volume2 size={20}/>Послушать образец</button>{!spoken&&!skipped?<><HoldMic onResult={text=>{if(normalizeWord(text)===word.word){setSpoken(true);setFeedback("Распознано: «"+text+"». Слово совпало! Теперь выбери картинку.");}else{setMistakes(m=>m+1);setFeedback("Распознано: «"+text+"». Попробуй произнести «"+word.word+"» ещё раз.");}}}/><button className="text-button speech-skip" onClick={()=>{setSkipped(true);setFeedback("Речь пропущена и не засчитана. Закрепим слово картинкой.");}}>Пропустить речь без оценки</button></>:<><p>{spoken?"Слово распознано. ":"Речь пропущена. "}Выбери подходящую картинку.</p><div className="picture-options">{wordOptions(state.index).map((i,n)=><button key={i} disabled={picture} aria-label={"Картинка "+(n+1)} className={picture&&i===state.index?"selected":""} onClick={()=>{if(i===state.index){setPicture(true);setFeedback("Верная картинка! "+word.word+" — "+word.ru);}else{setMistakes(m=>m+1);setFeedback("Эта картинка означает другое слово. Попробуй ещё раз.");}}}><WordImage index={i} hiddenLabel/><span>{n+1}</span></button>)}</div></>}</div>}
 {feedback&&<div className={"answer-feedback "+(correct||picture||spoken?"success":"")} aria-live="polite">{(correct||picture)&&<CheckCircle2 size={20}/>}<span>{feedback}</span></div>}<div className="workbench-footer"><span>{guest?"Гостевая тренировка":busy?"Сохраняем…":"Прогресс сохраняется после каждого слова"}</span><button className="btn primary" disabled={busy||!(state.stage===0||correct||state.stage===3&&picture)} onClick={()=>advance()}>{busy?"Сохраняем…":state.index===14?(state.stage===0?"Start checking":state.stage===3?"Завершить":"Следующий этап"):"Next"}<ArrowRight size={18}/></button></div>{error&&<p className="inline-error" role="alert">{error}</p>}</section></div></>}
 </div>;
}
