"use client";
import { useState, useEffect, useCallback } from "react";
import { ArrowUpRight, ArrowRight, BookOpen, Boxes, ChartNoAxesCombined, ChevronRight, Flame, GraduationCap, Headphones, House, Keyboard, Mic, Orbit, Sparkles, Target, Volume2, PenLine, Library, MoreHorizontal, ClipboardList, Languages, Settings } from "lucide-react";
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarProvider, SidebarTrigger, useSidebar } from "@/components/ui/sidebar";
import { Progress } from "@/components/ui/progress";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {Grammar,Vocabulary,Reading,Speaking,Typing,ProgressView,dayKey,speak,type Session,type Review,type Save} from "./practice";
import {Listening,Writing,ConversationLab,type Draft,type Bookmark} from "./extended-practice";
import {Books} from "./books";
import {Homework} from "./homework";
import {Pronunciation,Translator} from "./speech-tools";
import {Account,Avatar,type AccountData} from "./account";
const nav = [{id:"homework",name:"Домашнее задание",icon:ClipboardList},{id:"translator",name:"Переводчик",icon:Languages},{id:"account",name:"Мой аккаунт",icon:Settings},{id:"home",name:"Моя орбита",icon:House},{id:"grammar",name:"Грамматика",icon:GraduationCap},{id:"vocabulary",name:"Словарный запас",icon:Boxes},{id:"reading",name:"Чтение",icon:BookOpen},{id:"speaking",name:"Speaking studio",icon:Mic},{id:"listening",name:"Listening & подкасты",icon:Headphones},{id:"writing",name:"Writing studio",icon:PenLine},{id:"books",name:"Книжная полка",icon:Library},{id:"typing",name:"Тренажёр печати",icon:Keyboard},{id:"progress",name:"Мой прогресс",icon:ChartNoAxesCombined}];
const skills = [{id:"grammar",title:"Grammar",ru:"Пойми, как устроен язык",icon:GraduationCap,color:"blue",detail:"12 временных форм"},{id:"vocabulary",title:"Vocabulary",ru:"Находи нужные слова",icon:Boxes,color:"orange",detail:"Слова для реальной жизни"},{id:"reading",title:"Reading",ru:"Читай между строк",icon:BookOpen,color:"green",detail:"Истории и новые смыслы"},{id:"speaking",title:"Speaking",ru:"Пусть тебя услышат",icon:Mic,color:"purple",detail:"Практика без стеснения"},{id:"listening",title:"Listening",ru:"Настройся на живую речь",icon:Headphones,color:"cyan",detail:"Диалоги и подкасты"},{id:"writing",title:"Writing",ru:"Вырази свою мысль",icon:PenLine,color:"pink",detail:"Письма, истории, эссе"}];
export default function Home(){
 const [view,setView]=useState("home");
 const [account,setAccount]=useState<AccountData|null>(null);
 const reloadAccount=useCallback(async()=>{try{const r=await fetch("/api/account");const d=await r.json() as AccountData & {error?:string};if(!r.ok)throw new Error(d.error);setAccount(d);}catch(e){toast.error(e instanceof Error?e.message:"Не удалось загрузить профиль.");}},[]);
 useEffect(()=>{reloadAccount();},[reloadAccount]);
 useEffect(()=>{document.documentElement.dataset.motion=account?.profile?.motion===false?"off":"on";document.documentElement.dataset.accent=account?.profile?.accent||"en-GB";},[account]);
 const [drafts,setDrafts]=useState<Draft[]>([]),[bookmarks,setBookmarks]=useState<Bookmark[]>([]);
 const updateDraft=(promptId:string,text:string)=>setDrafts(ds=>[...ds.filter(d=>d.promptId!==promptId),{promptId,text,updatedAt:Date.now()}]);
 const [sessions,setSessions]=useState<Session[]>([]),[reviews,setReviews]=useState<Review[]>([]),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(""),[needsAuth,setNeedsAuth]=useState(false);
 const navigate=useCallback((id:string)=>{if(nav.some(n=>n.id===id)){setView(id);window.location.hash=id;window.scrollTo({top:0,behavior:"instant"});window.speechSynthesis?.cancel();}},[]);
 const reload=useCallback(async()=>{try{const r=await fetch("/api/progress");const d=await r.json() as {error?:string;sessions:Session[];reviews:Review[];drafts:Draft[];bookmarks:Bookmark[]};if(!r.ok){setNeedsAuth(r.status===401);throw new Error(d.error||"Не удалось загрузить прогресс")}setSessions(d.sessions);setReviews(d.reviews);setDrafts(existing=>{const incoming=d.drafts||[];return [...incoming.map(x=>{const local=existing.find(e=>e.promptId===x.promptId);return local&&local.updatedAt>x.updatedAt?local:x}),...existing.filter(e=>!incoming.some(x=>x.promptId===e.promptId))]});setBookmarks(d.bookmarks||[]);setLoaded(true);setNeedsAuth(false);setLoadError("");}catch(e){setLoadError(e instanceof Error?e.message:"Не удалось загрузить прогресс");}},[]);
 const save:Save=useCallback(async(data)=>{try{const r=await fetch("/api/progress",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const d=await r.json() as {error?:string;sessions:Session[];reviews:Review[];drafts:Draft[];bookmarks:Bookmark[]};if(!r.ok){if(r.status===401)setNeedsAuth(true);throw new Error(d.error||"Не удалось сохранить результат")}await reload();if(!data.action)toast.success("Занятие сохранено. Ещё один шаг вперёд!");}catch(e){toast.error(e instanceof Error?e.message:"Не удалось сохранить. Попробуйте снова.");throw e;}},[reload]);
 useEffect(()=>{const sync=()=>{const id=window.location.hash.slice(1);setView(nav.some(n=>n.id===id)?id:"home")};sync();window.addEventListener("hashchange",sync);reload();return()=>window.removeEventListener("hashchange",sync)},[reload]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const c=new AbortController();try{Promise.resolve(context.registerTool({name:"navigate_learning_section",description:"Open an ORBIT learning section. Does not complete lessons or change saved progress.",inputSchema:{type:"object",properties:{section:{type:"string",enum:nav.map(n=>n.id)}},required:["section"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||!nav.some(n=>n.id===input.section)||Object.keys(input).length!==1)throw new Error("Invalid section");navigate(input.section);await new Promise(resolve=>requestAnimationFrame(()=>resolve(null)));return {section:input.section}}},{signal:c.signal})).catch(()=>{});}catch{}return()=>c.abort()},[navigate]);
 const today=sessions.filter(s=>s.day===dayKey()).length;
 const xp=sessions.reduce((n,s)=>n+10+Math.round(s.score/s.total*10),0);
 const activeDays=new Set(sessions.map(s=>s.day));let streak=0;const streakDate=new Date();if(!activeDays.has(dayKey(streakDate)))streakDate.setDate(streakDate.getDate()-1);while(activeDays.has(dayKey(streakDate))){streak++;streakDate.setDate(streakDate.getDate()-1)}
 const dashboard=<Dashboard setView={navigate} today={today} sessions={sessions} goal={account?.profile?.dailyGoal||3} name={account?.profile?.name}/>;
 return <SidebarProvider style={{"--sidebar-width":"238px"} as React.CSSProperties}>
 <Sidebar className="orbit-sidebar"><SidebarHeader><a className="brand" href="/"><Orbit size={35}/><span>orbit<span className="brand-period">.</span></span></a><span className="brand-caption">YOUR ENGLISH UNIVERSE</span></SidebarHeader><SidebarContent><div className="nav-caption">ПРОСТРАНСТВО ОБУЧЕНИЯ</div><Navigation view={view} navigate={navigate}/></SidebarContent><SidebarFooter><div className="sidebar-note"><Sparkles size={21}/><strong>Маленький шаг.<br/>Большой новый мир.</strong><p>Каждое занятие приближает<br/>к свободному английскому.</p></div><button className="profile" onClick={()=>navigate("account")}><span className="avatar"><Avatar kind={account?.profile?.avatar}/></span><div><strong>{account?.profile?.name||"Мой аккаунт"}</strong><small>{account?.user?"Настройки профиля":"Войти или создать"}</small></div></button></SidebarFooter></Sidebar>
 <div className="app-main"><header className="topbar"><div className="breadcrumbs"><SidebarTrigger className="mobile-menu"/><span>Моё обучение</span><ChevronRight size={14}/><b>{nav.find(n=>n.id===view)?.name}</b></div><div className="top-actions"><span className="streak"><Flame size={19}/> {loaded?streak:"—"} {streak%10===1&&streak%100!==11?"день":streak%10>=2&&streak%10<=4&&(streak%100<12||streak%100>14)?"дня":"дней"}</span><span className="xp"><Sparkles size={17}/> {loaded?xp:"—"} XP</span><button className="mini-avatar" aria-label="Настройки аккаунта" onClick={()=>navigate("account")}><Avatar kind={account?.profile?.avatar}/></button></div></header>
 <main className="workspace">{loadError&&<div className="connection-banner" role="status"><span>{needsAuth?"Войди, чтобы сохранять занятия и повторять слова по расписанию.":loadError}</span>{needsAuth?<button className="text-button" onClick={()=>navigate("account")}>Войти в аккаунт <ArrowRight size={16}/></button>:<button className="text-button" onClick={reload}>Повторить</button>}</div>}{view==="homework"?<Homework/>:view==="translator"?<Translator/>:view==="account"?<Account account={account} reload={reloadAccount}/>:view==="home"?dashboard:view==="grammar"?<Grammar save={save} sessions={sessions}/>:view==="vocabulary"?<Vocabulary save={save} reviews={reviews}/>:view==="reading"?<Reading save={save} sessions={sessions}/>:view==="speaking"?<><Pronunciation/><Speaking save={save}/><ConversationLab save={save}/></>:view==="listening"?<Listening save={save} sessions={sessions}/>:view==="writing"?<Writing save={save} drafts={drafts} onDraft={updateDraft}/>:view==="books"?<Books save={save} bookmarks={bookmarks}/>:view==="typing"?<Typing save={save}/>:<ProgressView sessions={sessions} reviews={reviews} loaded={loaded} reload={reload}/>}<footer>ORBIT © 2026<span>A little progress, every day.</span><span>Сделано для твоего будущего</span></footer></main></div><MobileDock view={view} navigate={navigate}/><Toaster position="bottom-right" richColors/></SidebarProvider>
}
function Navigation({view,navigate}:{view:string;navigate:(id:string)=>void}){const {setOpenMobile}=useSidebar();return <nav aria-label="Разделы обучения">{nav.map(n=><button key={n.id} className={"nav-item "+(view===n.id?"active":"")} aria-current={view===n.id?"page":undefined} onClick={()=>{navigate(n.id);setOpenMobile(false)}}><n.icon size={20}/><span>{n.name}</span>{n.id==="speaking"&&<span className="new-badge">NEW</span>}</button>)}</nav>}
function Dashboard({setView,today,sessions,goal,name}:{setView:(id:string)=>void;today:number;sessions:Session[];goal:number;name?:string}){return <><div className="page-heading"><div><span className="eyebrow">LET’S MAKE PROGRESS</span><h1>{name?`${name}, твоя орбита`:"Твой английский. Твоя орбита"}<span>.</span></h1><p>Необязательно знать всё. Достаточно начать сегодня.</p></div><span className="date-chip">Твой следующий шаг — здесь <Sparkles size={16}/></span></div>
 <section className="homework-link"><div><span className="eyebrow">ТВОЙ СЛЕДУЮЩИЙ ШАГ</span><h2>15 слов. Четыре способа запомнить.</h2><p>Карточки, написание, перевод, произношение и картинки.</p></div><button className="btn primary" onClick={()=>setView("homework")}>Домашнее задание <ArrowRight size={18}/></button></section><div className="dashboard-columns"><div className="dashboard-primary"><section className="hero" onPointerMove={e=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const box=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty("--px",((e.clientX-box.left)/box.width-.5)*12+"px");e.currentTarget.style.setProperty("--py",((e.clientY-box.top)/box.height-.5)*9+"px");}} onPointerLeave={e=>{e.currentTarget.style.setProperty("--px","0px");e.currentTarget.style.setProperty("--py","0px")}}><img src="/orbit-hero.png" alt="Синяя орбита среди облаков"/><div className="hero-content"><span className="pill">ТВОЁ ПУТЕШЕСТВИЕ НАЧИНАЕТСЯ</span><h2>Ближе к миру.<br/>С каждым словом.</h2><p>Начни с Present Simple.<br/>Расскажи миру о себе.</p><button className="btn primary" onClick={()=>setView("grammar")}>Начать учиться <ArrowRight size={18}/></button></div><span className="hero-label">ENGLISH, WITHOUT LIMITS</span></section>
 <div className="section-title"><h2>Исследуй свой английский</h2><span>Шесть навыков. Одна цель.</span></div><div className="skill-grid">{skills.map(s=><button className={`skill-card ${s.color}`} key={s.id} onClick={()=>setView(s.id)}><div className="skill-card-top"><span className="skill-icon"><s.icon size={27}/></span><ArrowUpRight size={21}/></div><h3>{s.title}</h3><p>{s.ru}</p><div className="skill-bottom"><span>{s.detail}</span><ArrowRight size={17}/></div></button>)}</div>
 <section className="typing-banner"><div className="key-symbol"><Keyboard size={30}/></div><div><span className="eyebrow">НАЙДИ СВОЙ FLOW</span><h3>Думай на английском. Печатай в ритме.</h3><p>Тренируй точность и запоминай живые выражения.</p></div><button className="btn light" onClick={()=>setView("typing")}>Открыть тренажёр <ArrowUpRight size={17}/></button></section>
 <div className="section-title"><h2>Твой маршрут на сегодня</h2><span>15 минут для себя</span></div><div className="daily-plan">{[{n:"01",name:"Познакомься с Present Simple",desc:"Грамматика · Правило и практика",time:"5 мин",id:"grammar",icon:GraduationCap},{n:"02",name:"Слова, которые пригодятся сегодня",desc:"Vocabulary · Повседневная жизнь",time:"5 мин",id:"vocabulary",icon:Boxes},{n:"03",name:"Расскажи немного о себе",desc:"Speaking · Первое знакомство",time:"5 мин",id:"speaking",icon:Mic}].map(x=><button key={x.n} className="plan-row" onClick={()=>setView(x.id)}><span className="plan-number">{x.n}</span><x.icon size={21}/><div><strong>{x.name}</strong><p>{x.desc}</p></div><span>{x.time}</span><ChevronRight size={18}/></button>)}</div></div>
 <aside className="right-rail"><section className="goal-card"><div className="section-title"><h3>Цель на сегодня</h3><Target size={19}/></div><div className="goal-ring" style={{background:"conic-gradient(#557beb "+Math.min(100,today/goal*100)+"%, #eef2fa 0)",border:"none",padding:9}}><div><strong>{today}<span>/ {goal}</span></strong><small>занятия</small></div></div><h4>{today>=goal?"Цель на сегодня достигнута!":"Всё начинается с одного шага"}</h4><p>Дневная цель — {goal} {goal===1?"занятие":goal<5?"занятия":"занятий"}.<br/>и ты уже ближе к своей цели.</p><div className="week-days">{["П","В","С","Ч","П","С","В"].map((d,i)=><span key={i}>{d}<i className={sessions.some(s=>{const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7)+i);return s.day===dayKey(d)})?"active":""}>{sessions.some(s=>{const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7)+i);return s.day===dayKey(d)})?"✓":"·"}</i></span>)}</div></section><section className="word-card"><span className="eyebrow">СЛОВО В ФОКУСЕ <Sparkles size={16}/></span><h3>possibility</h3><div className="word-pronounce">/ˌpɒsəˈbɪləti/ <button aria-label="Произнести possibility" onClick={()=>speak("possibility")}><Volume2 size={18}/></button></div><p>возможность</p><blockquote>“Every new word opens<br/>a new possibility.”</blockquote><button className="text-button" onClick={()=>setView("vocabulary")}>Изучать слова <ArrowRight size={16}/></button></section><section className="tip-card"><Headphones size={22}/><h4>Привычка сильнее мотивации</h4><p>Пять минут каждый день полезнее, чем ожидание идеального момента.</p><span>STAY CURIOUS. KEEP GOING.</span></section></aside></div>
 </>}

function MobileDock({view,navigate}:{view:string;navigate:(id:string)=>void}){const {toggleSidebar}=useSidebar();return <nav className="mobile-dock" aria-label="Быстрые разделы">{[{id:"home",label:"Главная",icon:House},{id:"homework",label:"Задания",icon:ClipboardList},{id:"listening",label:"Слушать",icon:Headphones},{id:"speaking",label:"Говорить",icon:Mic}].map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>navigate(n.id)}><n.icon size={21}/><span>{n.label}</span></button>)}<button onClick={toggleSidebar}><MoreHorizontal size={22}/><span>Ещё</span></button></nav>}
