"use client";
import {useEffect,useRef,useState} from "react";
import {Volume2,Mic,Square,ArrowLeftRight,Copy} from "lucide-react";
import {Choice,speak} from "./practice";
export function useWordRecognition(onResult:(text:string)=>void){
 const [listening,setListening]=useState(false),[error,setError]=useState("");const recognition=useRef<any>(null),held=useRef(false),active=useRef(false),callback=useRef(onResult);callback.current=onResult;
 useEffect(()=>()=>{active.current=false;recognition.current?.abort();window.speechSynthesis?.cancel();},[]);
 function start(){if(recognition.current)return;const Constructor=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Constructor){setError("Распознавание не поддерживается. Попробуйте Chrome или Edge либо пропустите речь — она не будет засчитана.");return;}window.speechSynthesis?.cancel();setError("");held.current=true;active.current=true;const r=new Constructor();recognition.current=r;r.lang=document.documentElement.dataset.accent||"en-GB";r.interimResults=false;r.continuous=false;r.maxAlternatives=1;r.onstart=()=>{if(!held.current){r.stop();return;}setListening(true);};r.onresult=(e:any)=>{if(active.current)callback.current(String(e.results[0][0].transcript));};r.onerror=(e:any)=>{if(active.current)setError(e.error==="not-allowed"?"Доступ к микрофону запрещён. Разрешите его в настройках браузера.":e.error==="no-speech"?"Речь не услышана. Зажмите кнопку и произнесите слово ещё раз.":"Не удалось распознать речь. Попробуйте снова или пропустите этот шаг.");};r.onend=()=>{if(active.current)setListening(false);recognition.current=null;};try{r.start();}catch{recognition.current=null;setError("Микрофон недоступен. Попробуйте снова.");}}
 function stop(){held.current=false;recognition.current?.stop();setListening(false);}
 return {listening,error,start,stop};
}
export function HoldMic({onResult}:{onResult:(text:string)=>void}){const mic=useWordRecognition(onResult);return <div className="hold-mic-wrap"><button className={"hold-mic "+(mic.listening?"recording":"")} aria-label="Удерживайте для произношения" onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);mic.start();}} onPointerUp={mic.stop} onPointerCancel={mic.stop} onKeyDown={e=>{if((e.key===" "||e.key==="Enter")&&!e.repeat){e.preventDefault();mic.start();}}} onKeyUp={e=>{if(e.key===" "||e.key==="Enter"){e.preventDefault();mic.stop();}}} onBlur={mic.stop}>{mic.listening?<Square size={24}/>:<Mic size={24}/>}<span>{mic.listening?"Говори… отпусти, когда закончишь":"Зажми и произнеси"}</span></button>{mic.error&&<p role="alert" className="inline-error">{mic.error}</p>}<small>Распознавание может передавать аудио службе браузера. Проверяется слово, а не качество акцента.</small></div>}
export function Pronunciation(){const [text,setText]=useState("Hi! Nice to meet you."),[rate,setRate]=useState("Обычно"),[accent,setAccent]=useState("British · UK"),[heard,setHeard]=useState("");return <section className="pronunciation-panel"><div><span className="eyebrow">PRONUNCIATION LAB</span><h2>Напиши. Послушай. Повтори.</h2><p>Одно слово или фраза — сначала образец, затем твой голос.</p></div><label className="field">Текст на английском<textarea value={text} maxLength={400} onChange={e=>{setText(e.target.value);setHeard("");}} placeholder="Например: hi, deal, nice to meet you"/></label><div className="control-row"><Choice value={accent} onChange={setAccent} items={["British · UK","American · US"]} label="Акцент"/><Choice value={rate} onChange={setRate} items={["Медленно","Обычно"]} label="Скорость"/><button className="btn primary" disabled={!text.trim()} onClick={()=>{speak(text,rate==="Медленно"?.7:1,accent.includes("UK")?"en-GB":"en-US");}}><Volume2 size={18}/>Послушать</button><button className="btn light" onClick={()=>window.speechSynthesis?.cancel()}><Square size={16}/>Стоп</button></div><HoldMic onResult={setHeard}/>{heard&&<div className="answer-feedback">Распознано: <b>{heard}</b></div>}</section>}
export function Translator(){const [text,setText]=useState(""),[from,setFrom]=useState("en"),[result,setResult]=useState(""),[source,setSource]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const generation=useRef(0);const bytes=new TextEncoder().encode(text).length;async function translate(){const id=++generation.current;setBusy(true);setError("");setResult("");try{const r=await fetch("/api/translate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,from})});const d=await r.json() as {error?:string;text:string;source:string};if(id!==generation.current)return;if(!r.ok)throw new Error(d.error);const decoded=new DOMParser().parseFromString(d.text,"text/html").documentElement.textContent||d.text;setResult(decoded);setSource(d.source);}catch(e){if(id===generation.current)setError(e instanceof Error?e.message:"Не удалось перевести.");}finally{if(id===generation.current)setBusy(false);}}
 return <><div className="page-heading"><div><span className="eyebrow">TRANSLATOR</span><h1>От слова к смыслу.</h1><p>Английский ↔ русский. Перевод и произношение в одном месте.</p></div></div><div className="translator-surface"><div className="translator-head"><strong>{from==="en"?"Английский":"Русский"}</strong><button className="icon-button" aria-label="Поменять языки" onClick={()=>{generation.current++;setBusy(false);setFrom(from==="en"?"ru":"en");setText(result);setResult("");setError("");}}><ArrowLeftRight/></button><strong>{from==="en"?"Русский":"Английский"}</strong></div><div className="translation-columns"><label className="translation-input"><span className="sr-only">Текст для перевода</span><textarea value={text} maxLength={500} placeholder="Напиши слово или короткую фразу…" onChange={e=>{generation.current++;setBusy(false);setText(e.target.value);setResult("");setError("");}}/><small>{bytes} / 500 байт</small></label><div className="translation-output" aria-live="polite">{busy?"Ищем подходящий перевод…":result||"Здесь появится перевод"}{result&&<><small>{source}</small><div className="control-row"><button className="btn light" onClick={()=>{const u=new SpeechSynthesisUtterance(result);u.lang=from==="en"?"ru-RU":"en-GB";window.speechSynthesis?.cancel();window.speechSynthesis?.speak(u);}}><Volume2 size={18}/>Послушать</button><button className="btn light" onClick={async()=>{try{await navigator.clipboard.writeText(result);setSource("Скопировано");}catch{setError("Не удалось скопировать. Выделите текст вручную.");}}}><Copy size={16}/>Копировать</button></div></>}</div></div><div className="translator-footer"><p>Сначала ищем в словаре ORBIT. Другие фразы отправляются в <a href="https://mymemory.translated.net/doc/" target="_blank" rel="noreferrer">MyMemory</a> по нажатию кнопки. У машинного перевода возможны неточности.</p><button className="btn primary" disabled={busy||!text.trim()||bytes>500} onClick={translate}>Перевести <ArrowLeftRight size={18}/></button></div>{error&&<p role="alert" className="inline-error">{error}</p>}</div></>;
}
